### ISSUE TITLE
Expanding the IonAnnotation based on the mzTab format

### ISSUE THREAD

**Issue by dyrlund** [msdk/msdk#108]
In the current mzTab format (v. 1.0.0) there are mandatory columns for small molecules which are currently not supported in the `IonAnnotation` - see page 13 in the [mzTab Specifications](https://mztab.googlecode.com/svn/specification_document-releases/version-1.0.0/mzTab_format_specification.pdf). These are:
- inchi_key
- taxid
- species
- database
- database version
- spectra_ref
- search_engine
- best_search_engine_score
- modifications
- reliability

I think this information will make it more transparent where identifications are coming from when using multiple identification methods. Furthermore, it will also provide some of the structure needed to implement MS/MS identification methods.

What do you think about adding support for this in MSDK?

**Comment by tomas-pluskal** [comment]
I agree it is useful.

**Comment by dyrlund** [comment]
We should also add the following two:

- smiles
- inchi_key

**Comment by dyrlund** [comment]
Based on the mzTab specifications, I suggest to use the following class types:

- smiles - String
- inchi_key - String
- taxid - Integer
- species - String
- database - String
- database_version - String
- spectra_ref - String
- search_engine - String
- best_search_engine_score - Double
- modifications - String
- reliability - Integer

Any objections against that? And any suggestions about how we best make the change in MSDK?

Adding them all seperately to the IonAnnotation is the simplest but this will not take into account that the following are related:
- taxid and species
- database and database_version

**Comment by dyrlund** [comment]
@tomas-pluskal Any comments about how we best make the changes in MSDK?

**Comment by dyrlund** [comment]
I have made the changes as suggested above in #121. Please let me know what you think.
