### ISSUE TITLE
Request a CV Term for PSI-MS

### ISSUE THREAD

**Issue by nilshoffmann** [msdk/msdk#140]
File a request to the psi-ms dev mailing list (psidev-ms-dev@lists.sourceforge.net), requesting a new term for MSDK:
[Term]
id: MS:100XXXX
name: MSDK
def: "Mass Spectrometry Development Kit (MSDK) is a Java library of algorithms for processing mass spectrometry data." [PSI:PI, http://msdk.github.io/]
is_a: MS:1001456 ! analysis software
is_a: MS:1001457 ! data processing software

Once this has been added, we should adapt the MZML output created by MSDK to contain the CV term.

**Comment by nilshoffmann** [comment]
https://github.com/msdk/msdk/blob/master/msdk-io/msdk-io-mzml/src/main/java/io/github/msdk/io/mzml/MzMLFileExportMethod.java

**Comment by tomas-pluskal** [comment]
Good idea, Nils. 
Can you request the term from PSI-MS? I can update the mzML export.

**Comment by nilshoffmann** [comment]
Request has been sent and is currently pending.

**Comment by nilshoffmann** [comment]
MSDK term is part of PSI-MS CV from version 3.86.0 onwards:

    +[Term]
    +id: MS:1002645
    +name: MSDK
    +def: "Mass Spectrometry Development Kit (MSDK) is a Java library of algorithms for processing of mass spectrometry data." [PSI:PI, http://msdk.github.io/]
    +is_a: MS:1001456 ! analysis software
    +is_a: MS:1001457 ! data processing software

Latest version is available here:
https://github.com/HUPO-PSI/psi-ms-CV/blob/master/psi-ms.obo
