### ISSUE TITLE
Cannot build due to jmzml 1.7.5 dependency

### ISSUE THREAD

**Issue by TDI-tenderholt** [msdk/msdk#143]
Here's the relevant stack trace from ```mvn compile```:

> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.268 s
[INFO] Finished at: 2016-09-06T13:37:19-07:00
[INFO] Final Memory: 12M/113M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project msdk-io-mzml: Could not resolve dependencies for project io.github.msdk:msdk-io-mzml:jar:0.0.7-SNAPSHOT: Failed to collect dependencies at uk.ac.ebi.jmzml:jmzml:jar:1.7.5: Failed to read artifact descriptor for uk.ac.ebi.jmzml:jmzml:jar:1.7.5: Could not transfer artifact uk.ac.ebi.jmzml:jmzml:pom:1.7.5 from/to nexus-ebi-release-repo (http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/): Failed to transfer file: http://www.ebi.ac.uk/Tools/maven/repos/content/groups/ebi-repo/uk/ac/ebi/jmzml/jmzml/1.7.5/jmzml-1.7.5.pom. Return code is: 500 , ReasonPhrase:Internal Server Error. -> [Help 1]

This is after a fresh update to master (i.e. commit ```790eb96```).

After a bit of searching, I see the jmzml documentation suggests the following maven dependency info, however, visiting their repo doesn't have the 1.7.5 version:

```
        <repository>
            <id>ebi-repo</id>
            <name>The EBI Maven 2 repository</name>
            <url>http://www.ebi.ac.uk/~maven/m2repo</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

        <dependency>
            <groupId>uk.ac.ebi.jmzml</groupId>
            <artifactId>jmzml</artifactId>
            <version>x.y.z</version>
        </dependency>
```

Is there a more recent repo that contains 1.7.5? Or is the build supposed to happen with 1.7.4?

**Comment by tomas-pluskal** [comment]
It seems EBI is constantly having issues with their maven repo... I filed a ticket here: 
https://github.com/PRIDE-Utilities/jmzml/issues/18
You can change the version to 1.7.4 and it should compile.

**Comment by TDI-tenderholt** [comment]
If this is an ongoing problem, what about using git submodules to directly pull in their released code?

**Comment by TDI-tenderholt** [comment]
FYI, this is what I was thinking: https://github.com/Veritomyx/msdk/tree/ebi-submodules/third-party. Unfortunately, jmzml depends on other EBI libraries which can't be found because of their repo problems.

**Comment by tomas-pluskal** [comment]
Some details about the EBI downtime: https://github.com/PRIDE-Utilities/ols-client/issues/18

**Comment by TDI-tenderholt** [comment]
Thanks for the info. I'll just be patient while EBI fixes their repos.

**Comment by tomas-pluskal** [comment]
The EBI repo should be up again.

**Comment by TDI-tenderholt** [comment]
Thanks for the info. I'm able to build msdk now.
