### ISSUE TITLE
MgfExportAlgorithm isn't a MSDKMethod?

### ISSUE THREAD

**Issue by TDI-tenderholt** [msdk/msdk#149]
I noticed that [```MgfExportAlgorithm```](https://github.com/msdk/msdk/blob/master/msdk-io/msdk-io-mgf/src/main/java/io/github/msdk/io/mgf/MgfExportAlgorithm.java) isn't a ```MSDKMethod``` like some of the other I/O classes. Is this intentional? Or something that should be fixed?

**Comment by tomas-pluskal** [comment]
MSDKMethod is good for things that take some time to finish, so you can track progress and cancel them if necessary. The MGF export is so fast that it does not make sense to track its progress. That said, I have no problem with changing it to MSDKMethod, if you wish.

**Comment by TDI-tenderholt** [comment]
Is it fast enough on a LC/MS run with thousands of scans? I haven't really played with it, but we've been discussing MGF export and had a recent collaboration that had over 34,000 MS2 scans.

**Comment by tomas-pluskal** [comment]
Putting 34,000 spectra into an MGF file sounds like an abomination :) 
But yes, I do agree that in such case it might be better to switch it to MSDKMethod with progress tracking and everything.

**Comment by TDI-tenderholt** [comment]
Do you think the current static ```exportSpectrum``` and ```exportSpectra``` methods should be kept? It looks like MZmine3 uses the latter.

**Comment by tomas-pluskal** [comment]
You can remove them, I will update MZmine 3 accordingly.
