### ISSUE TITLE
Bug in TxtExportAlgorithm.exportSpectra() ?

### ISSUE THREAD

**Issue by TDI-tenderholt** [msdk/msdk#153]
It appears that [`TxtExportAglorithm.exportSpectra()`](https://github.com/msdk/msdk/blob/master/msdk-io/msdk-io-txt/src/main/java/io/github/msdk/io/txt/TxtExportAlgorithm.java#L55) will concatenate the output from multiple spectra into a single file without any line break between spectra. The only way to tell there are multiple spectra is to look for discontinuities in the m/z values. Is that intentional? If so, note that will probably not work in the perhaps-unlikely general case (e.g. spectrum 1 is 200-500, spectrum 2 is 505-800, etc.).

**Comment by tomas-pluskal** [comment]
True. We can add an extra line separator in between the spectra.
