### ISSUE TITLE
MzTabFileExportMethod does not write inchi key to mzTab file

### ISSUE THREAD

**Issue by meier-rene** [msdk/msdk#162]
Please also export the inchiKey string to the mzTab File if its set in IonAnnotation-Object. The code is missing in MzTabFileExportMethod.writeSampleData, but should be straight forward to add by using SmallMolecule.setInchiKey(String inchiKeyLabel).

**Comment by tomas-pluskal** [comment]
Added in commit https://github.com/msdk/msdk/commit/946ae694af306465b6b38ac53206accbedcd74a4
