### ISSUE TITLE
MSDK structure

### ISSUE THREAD

**Issue by robinschmid** [msdk/msdk#251]
Hey MZmine community,

as far as I understand the structure of the MSDK, it is a maven project with multiple modules. Is there any smart way to import this project into eclipse? After importing it as a Maven project, the development does feel unnatural and the structure is very confusing (see below). (It is my first time working on a multi module maven project) 

Is Java 9 and project Jigsaw changing any future plans for the final module structure of the MSDK?

Best regards,
Robin

![image](https://user-images.githubusercontent.com/10366914/34948748-54d9090e-fa0e-11e7-8ee7-63804b3d2ac3.png)

**Comment by tomas-pluskal** [comment]
Hi Robin,

This is how it looks in my Eclipse:

<img width="368" alt="screen shot 2018-01-15 at 10 53 19" src="https://user-images.githubusercontent.com/1796692/34950866-652d8c66-f9e2-11e7-9d06-5efec913cb00.png">

It seems your src/main/java is not recognized as a source directory by Eclipse. This should be automatic if the project is imported as a Maven project. Try right click on the project name -> Maven -> Convert to Maven project or something like that, or Update project.

Also you can enable hierarchical representation of packages, it looks better:
<img width="419" alt="screen shot 2018-01-15 at 10 55 37" src="https://user-images.githubusercontent.com/1796692/34950950-ac4dc58e-f9e2-11e7-8703-a84ab088f1a2.png">

As for Java 9-style modules, at this point I don't see any advantage in converting MSDK to Java 9.

**Comment by tomas-pluskal** [comment]
Also it seems you are looking at old sources? There is no msdk-featdet package anymore, see https://github.com/msdk/msdk

**Comment by robinschmid** [comment]
Oh yeah, I have tried to refork MSDK and was still working on an older version. Thank you. 
Maybe the only strange thing is that it does not recognise the main (parent) msdk project as a project with source folders.

Alright, good to hear your opinion on Java 9 and your plans for the module system.
