### ISSUE TITLE
Tracking MzMLUnmarshaller() progress for mzML file import

### ISSUE THREAD

**Issue by dyrlund** [msdk/msdk#27]
When importing mzML files, running MzMLUnmarshaller() takes a significant amount of time compared to the rest of the import code (e.g. 6 seconds vs. 5 seconds). During this time, getFinishedPercentage() is not updated. Any suggestions on how to improve this?

Here is a link to [MzMLFileImportMethod.java](https://github.com/msdk/msdk/blob/master/msdk-io/msdk-mzmlimport/src/main/java/io/github/msdk/io/rawdataimport/mzml/MzMLFileImportMethod.java) and [MzMLUnmarshaller.java](https://github.com/PRIDE-Utilities/jmzml/blob/master/src/main/java/uk/ac/ebi/jmzml/xml/io/MzMLUnmarshaller.java).

**Comment by nilshoffmann** [comment]
Hi,
if I recall correctly from Maltcms' jmzl DataSource, the jmzml library
itself spends a large amount of time unmarshalling
the structure of the mzML file and creating its internal index. This
seems to work faster with pre-indexed mzML files, which are, afaik, not
creatable with the jmzml implementation, but for example with
proteowizard. I guess that without some sort of rewriting of jmzml
unmarshalling, there will be no way of improving this much on first-time
reads.

Best regards,
Nils
 
Am 06.11.15 um 13:47 schrieb Thomas F. Dyrlund:

**Comment by tomas-pluskal** [comment]
I think the proper solution in long-term would be to fork the jmzml project (which seems to be quite dead, anyway) and improve it. Perhaps it could even be fully integrated into MSDK, if the authors agree. That's not a priority right now, though.

**Comment by tomas-pluskal** [comment]
Closing since we have a new mzML parser
