### ISSUE TITLE
Importing MSDK into eclipse

### ISSUE THREAD

**Issue by SteffenHeu** [msdk/msdk#273]
Hey,

what is the recommended way to import the MSDK into eclipse? I did not find any .project file in the directory so I figured I'd just ask. 
Do you just import it as a maven project or is there a better way?

Best regards
Steffen

**Comment by tomas-pluskal** [comment]
Hi @SteffenHeu 
Just import is as a Maven project, it works totally fine. You will get a separate Eclipse project for each MSDK module, that is fine and expected.

**Comment by SteffenHeu** [comment]
Ok, thank you.
