### ISSUE TITLE
Exception in io.github.msdk.io.nativeformats.ThermoRawImportMethod

### ISSUE THREAD

**Issue by KSachi** [msdk/msdk#275]
I am trying to parse a raw file using ThermoRawImportMethod.

The exception can be reproduced this way:
```
ThermoRawImportMethod th = new ThermoRawImportMethod(file);
th.execute(); // Exception occurs here
```

Apparently, it stems from the exe file being run behind the scenes. The error message says

`ERROR: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 800736b1.`

I already made sure that I have the newest .NET framework running.

When I try to directly execute the `ThermoRawDump.exe` with the raw file path as argument I get the same error.

Any help is much appreciated. Thanks in advance.

**Comment by tomas-pluskal** [comment]
I think the Thermo MSFileReader library that is used here has some dependencies that we haven't fully tracked down..

Try installing Proteowizard (http://proteowizard.sourceforge.net), it will install the dependencies that these vendor libraries require. After that the MSDK module might work for you.

Another approach might be using this project instead:
https://github.com/compomics/ThermoRawFileParser

**Comment by KSachi** [comment]
I installed Proteowizard, that didnt solve anything. I then replaced the thermorawdump exe in the original package with the one in the second link.  I am now getting the following error:

``INFO: Started parsing file C:\Users .....
io.github.msdk.MSDKException:  i.o.github.msdk.MSDKException : No scans found ``

I tried out the parser using files downloaded from MetaboLights, that is, manually curated and validated files from published studies and I would doubt that they have no scans.  Any ideas on how I could move forward ?

**Comment by tomas-pluskal** [comment]
The ThermoRawFileParser is not a direct replacement for the thermorawdump.exe program, it's just another project that does a similar thing. The "no scans found" simply means you cannot use ThermoRawFileParser in this way.

I don't know why the thermorawdump program doesn't work for you. But if you find out, let us know so we can fix it for everyone else.

**Comment by KSachi** [comment]
I tried out all the parsers that come with the MSDK and the all the other ones work perfectly (.netcdf , waters and mzml parsers) except for the ThermoRawFileParser on a Windows 10 with all requirements installed (.Net frameworks plus MSFileReader and Proteowizard etc).plus Intellij Idea 2019.3 and running Java 13. I have also tried running the python bindings of the MSFileReader and it works fine with no problem but the run time is almost 2 hours for a single file.

Running the ThermoRawFileParser from Componics from the commandline also produced the following error:
`ERROR: System.Runtime.InteropServices.COMException (0x800736B1): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 800736b1.`

The weird thing is, the parser works fine on another windows 10 machine with Java 10 and IntelliJ Idea 2018.3 and is extremely fast, parsing a file in less than 2 minutes.   I hope this helps you in figuring out where the problem lies.

**Comment by KSachi** [comment]
@tomas-pluskal I might have found a solution, some of these dependencies that you haven't tracked down seem to come installed with MATLAB. As soon as I uninstalled MATLAB on my other pc, the parser function stopped working and as soon as I installed it, it started working fine again. I hope this information might help you track down the dependencies that are missing.
