### ISSUE TITLE
MS/MS feature list builder

### ISSUE THREAD

**Issue by dyrlund** [msdk/msdk#31]
Hi all

I have been thinking about how to best implement the MS/MS feature list builder and suggest that we do it in a different way compared to MZmine 2.

This is the workflow I suggest:

1. Find all MS/MS precursor ions in the raw data file and generate a list of m/z, RT and total MS/MS spectra intensity.
2. Sort the list by total MS/MS spectra intensity.

3. Go through all the m/z values in the list and remove m/z values with lower intensity and with a m/z within x ppm.

4. Use the m/z and RT list as an input for the targeted detection method to generate the feature table.

What do you think?

**Comment by sneumann** [comment]
Hi, would there be different MS/MS feature list builders 
for targeted MS/MS, DDA, DIA (MSe and SWATH) ? 
To which does the workflow above belong ?
Yours,
Steffen

**Comment by dyrlund** [comment]
I was thinking about DDA methods which include MS1 and MS2 scans and where a narrow isolation window was selected for MS2. For DIA methods there should be a seperate builder and likewise for SRM / MRM methods as these will require different algorithms.

**Comment by tomas-pluskal** [comment]
Thomas, I think it's a good idea to take advantage of the existing targeted detection module, instead of duplicating the functionality.

**Comment by dyrlund** [comment]
I added the new MS/MS feature detection module in pull request #61.
