### ISSUE TITLE
Still data point list strange behaviour

### ISSUE THREAD

**Issue by SandraCastilloPriego** [msdk/msdk#54]
MsSpectrumDataPointList newDataPoints = MSDKObjectBuilder.getMsSpectrumDataPointList(); newScan.getDataPoints(newDataPoints);

 float sumInt = 0;
 for(MsIon ion : newDataPoints){
                sumInt+=ion.getIntensity();
 }
 Assert.assertEquals(sumInt, newScan.getTIC(),0.001);

It fails the test. The sum of intensities is different than TIC... why?

**Comment by tomas-pluskal** [comment]
Hi Sandra,

I added a test for this in pull request #56, but the test passes fine for me.
Can you add the test to the module where you see this strange behavior? Then I can take a look at why it's failing.

**Comment by SandraCastilloPriego** [comment]
Hmm, weird, it doesn't happen now.. I must have done something wrong..
